<a href="https://colab.research.google.com/github/zavyalov-daniil/omsu_ml_zav/blob/main/06_hw_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Worshop 2.1 Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [2]:
import numpy as np
print(np.__version__)

1.21.6


2) Создать нулевой вектор размера 10

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3) Создать вектор заполненный 7-ами размера 7

In [4]:
np.full(7, 7)

array([7, 7, 7, 7, 7, 7, 7])

4) Создать вектор заполненный четными числами от 10 до 100

In [5]:
np.arange(10,101,2)

array([ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,  34,
        36,  38,  40,  42,  44,  46,  48,  50,  52,  54,  56,  58,  60,
        62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,  84,  86,
        88,  90,  92,  94,  96,  98, 100])

5) Создать массив случайных чисел и развернуть его задом наперёд

In [15]:
arr = np.random.randn(4)
print(arr)
arr[::-1]

[-0.40796182  1.26122997  1.06017453  1.60776776]


array([ 1.60776776,  1.06017453,  1.26122997, -0.40796182])

6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [18]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [20]:
np.eye(5)[1:5,0:4]

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [30]:
m1 = np.full((7,7), 7)
m2 = np.diag(np.random.randint(3,7, size=7))
m1 - m2

array([[4, 7, 7, 7, 7, 7, 7],
       [7, 1, 7, 7, 7, 7, 7],
       [7, 7, 4, 7, 7, 7, 7],
       [7, 7, 7, 2, 7, 7, 7],
       [7, 7, 7, 7, 4, 7, 7],
       [7, 7, 7, 7, 7, 4, 7],
       [7, 7, 7, 7, 7, 7, 3]])

9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [31]:
x = np.zeros((5,5))
x + np.arange(5)

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [49]:
m = np.random.randint(10, size=(10,10))
print(m)
m - m.mean(axis=1, keepdims=True)

[[9 1 2 6 5 7 5 3 3 6]
 [4 9 2 0 2 3 0 6 6 9]
 [1 8 8 4 2 5 7 1 6 7]
 [6 7 9 2 2 0 2 1 6 8]
 [8 5 8 2 5 4 2 7 4 7]
 [9 7 6 5 1 0 3 3 8 3]
 [6 7 8 2 0 0 8 3 1 8]
 [3 1 4 3 7 8 6 5 5 8]
 [4 5 2 4 2 8 7 5 6 4]
 [3 1 5 1 1 9 0 9 3 4]]


array([[ 4.3, -3.7, -2.7,  1.3,  0.3,  2.3,  0.3, -1.7, -1.7,  1.3],
       [-0.1,  4.9, -2.1, -4.1, -2.1, -1.1, -4.1,  1.9,  1.9,  4.9],
       [-3.9,  3.1,  3.1, -0.9, -2.9,  0.1,  2.1, -3.9,  1.1,  2.1],
       [ 1.7,  2.7,  4.7, -2.3, -2.3, -4.3, -2.3, -3.3,  1.7,  3.7],
       [ 2.8, -0.2,  2.8, -3.2, -0.2, -1.2, -3.2,  1.8, -1.2,  1.8],
       [ 4.5,  2.5,  1.5,  0.5, -3.5, -4.5, -1.5, -1.5,  3.5, -1.5],
       [ 1.7,  2.7,  3.7, -2.3, -4.3, -4.3,  3.7, -1.3, -3.3,  3.7],
       [-2. , -4. , -1. , -2. ,  2. ,  3. ,  1. ,  0. ,  0. ,  3. ],
       [-0.7,  0.3, -2.7, -0.7, -2.7,  3.3,  2.3,  0.3,  1.3, -0.7],
       [-0.6, -2.6,  1.4, -2.6, -2.6,  5.4, -3.6,  5.4, -0.6,  0.4]])

11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [53]:
m = np.random.randint(10, size=(10,10))
print(m)
m - np.median(m, axis=1, keepdims=True) 

[[4 1 9 6 3 6 3 5 3 9]
 [3 2 0 9 4 6 5 0 5 3]
 [6 8 8 7 2 3 2 3 4 2]
 [5 0 8 8 5 8 8 8 8 6]
 [1 8 3 8 2 2 6 7 3 8]
 [8 0 7 8 4 9 5 3 1 4]
 [1 0 8 7 9 6 2 2 4 1]
 [8 0 7 4 3 0 5 9 0 2]
 [1 3 8 9 4 2 7 9 4 6]
 [2 3 4 6 3 7 1 2 4 9]]


array([[-0.5, -3.5,  4.5,  1.5, -1.5,  1.5, -1.5,  0.5, -1.5,  4.5],
       [-0.5, -1.5, -3.5,  5.5,  0.5,  2.5,  1.5, -3.5,  1.5, -0.5],
       [ 2.5,  4.5,  4.5,  3.5, -1.5, -0.5, -1.5, -0.5,  0.5, -1.5],
       [-3. , -8. ,  0. ,  0. , -3. ,  0. ,  0. ,  0. ,  0. , -2. ],
       [-3.5,  3.5, -1.5,  3.5, -2.5, -2.5,  1.5,  2.5, -1.5,  3.5],
       [ 3.5, -4.5,  2.5,  3.5, -0.5,  4.5,  0.5, -1.5, -3.5, -0.5],
       [-2. , -3. ,  5. ,  4. ,  6. ,  3. , -1. , -1. ,  1. , -2. ],
       [ 4.5, -3.5,  3.5,  0.5, -0.5, -3.5,  1.5,  5.5, -3.5, -1.5],
       [-4. , -2. ,  3. ,  4. , -1. , -3. ,  2. ,  4. , -1. ,  1. ],
       [-1.5, -0.5,  0.5,  2.5, -0.5,  3.5, -2.5, -1.5,  0.5,  5.5]])

12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [66]:
m = np.random.randint(10, size=(5,5))
print(m)
mx = np.amax(m, axis=1, keepdims=True)
mn = np.amin(m, axis=1, keepdims=True)
np.concatenate((m,mx, mn), axis=1)

[[7 4 2 5 5]
 [1 3 0 1 8]
 [1 3 0 4 9]
 [0 7 6 4 4]
 [3 1 4 7 5]]


array([[7, 4, 2, 5, 5, 7, 2],
       [1, 3, 0, 1, 8, 8, 0],
       [1, 3, 0, 4, 9, 9, 0],
       [0, 7, 6, 4, 4, 7, 0],
       [3, 1, 4, 7, 5, 7, 1]])

13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

In [78]:
m = np.arange(1,51)
a = m[m%2!=0].reshape((5,5))
b= m[m%2==0].reshape((5,5))
print(a)
print(b)
p=np.matmul(a,b)
print(p)
#p1=np.linalg.inv(p)

[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]
 [41 43 45 47 49]]
[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]]
[[ 750  800  850  900  950]
 [1850 2000 2150 2300 2450]
 [2950 3200 3450 3700 3950]
 [4050 4400 4750 5100 5450]
 [5150 5600 6050 6500 6950]]


14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами. 

In [80]:
x = np.zeros((8, 8))
x[::2, 1::2] = 1
x[1::2, ::2] = 1
print(x)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]
